const traits = [
  'Brave','Curious','Determined','Loyal','Independent','Compassionate','Clever','Patient','Ambitious','Calm','Bold','Honest','Playful','Disciplined','Resourceful','Protective','Fearless','Observant','Adaptable','Confident','Creative','Persistent','Kind','Strategic','Adventurous','Selfless','Competitive','Thoughtful','Rebellious','Focused','Optimistic','Cautious','Charismatic','Practical','Empathetic','Resilient','Inventive','Daring','Reliable','Mysterious','Leader','Free-Spirited','Analytical','Passionate','Tactical','Patiently Bold','Witty','Vigilant','Tenacious','Open-Minded'
];
const state={name:'',age:16,traits:[],level:1,xp:0,coins:0,energy:100,textColor:'#e7e7e7',sound:true};
const $=id=>document.getElementById(id);
const traitPool=$('trait-pool'),traitCount=$('trait-count'),startButton=$('start-button'),creationError=$('creation-error'),creationScreen=$('creation-screen'),reviewScreen=$('review-screen'),gameScreen=$('game-screen');
traits.forEach((trait,index)=>{const b=document.createElement('button');b.type='button';b.className='trait';b.textContent=trait;b.dataset.trait=trait;b.dataset.index=index;b.addEventListener('click',()=>toggleTrait(trait,b));traitPool.appendChild(b);});
function refreshStart(){startButton.disabled=state.traits.length!==3||!$('player-name').value.trim();traitCount.textContent=`${state.traits.length} / 3`;}
function toggleTrait(trait,button){if(state.traits.includes(trait)){state.traits=state.traits.filter(t=>t!==trait);button.classList.remove('selected');}else{if(state.traits.length>=3)return;state.traits.push(trait);button.classList.add('selected');}creationError.hidden=true;refreshStart();}
$('player-name').addEventListener('input',refreshStart);
$('character-form').addEventListener('submit',e=>{e.preventDefault();const name=$('player-name').value.trim(),age=Number($('player-age').value);if(!name||state.traits.length!==3||age<10||age>30){creationError.textContent='Complete your name, age, and choose exactly three traits.';creationError.hidden=false;return;}state.name=name;state.age=age;showReview();});
function showReview(){creationScreen.hidden=true;reviewScreen.hidden=false;$('review-name').textContent=state.name;$('review-age').textContent=state.age;const list=$('review-trait-list');list.innerHTML='';state.traits.forEach((trait,i)=>{const item=document.createElement('div');item.className='review-trait';item.innerHTML=`<span>${String(i+1).padStart(2,'0')}</span><strong>${trait}</strong>`;list.appendChild(item);});}
$('back-to-creation').addEventListener('click',()=>{reviewScreen.hidden=true;creationScreen.hidden=false;});
$('confirm-character').addEventListener('click',beginGame);
function beginGame(){reviewScreen.hidden=true;gameScreen.hidden=false;updateStats();appendStory(`Welcome, ${state.name}.`,'system');appendStory('Paris is waiting. Chapter 1 will begin here.');appendStory('Your three traits have been recorded for the future Miraculous-matching system.','system');renderChoice('Begin your story',()=>appendStory('Chapter 1 will begin here.','system'));}
function appendStory(text,type=''){const entry=document.createElement('p');entry.className=`story-entry ${type}`;entry.textContent=text;$('story-log').appendChild(entry);entry.scrollIntoView({behavior:'smooth',block:'nearest'});}
function renderChoice(label,handler){const b=document.createElement('button');b.className='choice';b.type='button';b.textContent=label;b.addEventListener('click',handler);$('choices').appendChild(b);}
function updateStats(){$('stats-name').textContent=state.name||'Player';$('stats-level').textContent=`Level ${state.level}`;$('stat-xp').textContent=`${state.xp} / 100`;$('stat-coins').textContent=state.coins;$('stat-energy').textContent=`${state.energy} / 100`;$('stat-miraculous').textContent='Undiscovered';}
$('open-stats').addEventListener('click',()=>$('stats-panel').classList.remove('closed'));$('close-stats').addEventListener('click',()=>$('stats-panel').classList.add('closed'));
const settingsDialog=$('settings-dialog');$('settings-toggle').addEventListener('click',()=>settingsDialog.showModal());$('close-settings').addEventListener('click',()=>settingsDialog.close());
$('text-color').addEventListener('input',e=>{state.textColor=e.target.value;document.documentElement.style.setProperty('--text',state.textColor);});
$('sound-toggle').addEventListener('click',e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'🔊':'🔇';e.currentTarget.setAttribute('aria-pressed',String(state.sound));});
// Personality-to-Miraculous compatibility will be added with the story data rather than invented in the UI layer.
