const traits=['Brave','Curious','Determined','Loyal','Independent','Compassionate','Clever','Patient','Ambitious','Calm','Bold','Honest','Playful','Disciplined','Resourceful','Protective','Fearless','Observant','Adaptable','Confident','Creative','Persistent','Kind','Strategic','Adventurous','Selfless','Competitive','Thoughtful','Rebellious','Focused','Optimistic','Cautious','Charismatic','Practical','Empathetic','Resilient','Inventive','Daring','Reliable','Mysterious','Leader','Free-Spirited','Analytical','Passionate','Tactical','Patiently Bold','Witty','Vigilant','Tenacious','Open-Minded'];
const state={name:'',age:14,traits:[],textColor:'#e7e7e7',sound:true};
const $=id=>document.getElementById(id),pool=$('trait-pool'),count=$('trait-count'),start=$('start-button'),error=$('creation-error');
traits.forEach((trait,index)=>{const b=document.createElement('button');b.type='button';b.className='trait';b.textContent=trait;b.dataset.trait=trait;b.dataset.index=index;b.addEventListener('click',()=>toggleTrait(trait,b));pool.appendChild(b)});
function refresh(){start.disabled=state.traits.length!==3||!$('player-name').value.trim();count.textContent=`${state.traits.length} / 3`}
function toggleTrait(trait,b){if(state.traits.includes(trait)){state.traits=state.traits.filter(t=>t!==trait);b.classList.remove('selected')}else{if(state.traits.length>=3)return;state.traits.push(trait);b.classList.add('selected')}error.hidden=true;refresh()}
$('player-name').addEventListener('input',refresh);
$('character-form').addEventListener('submit',e=>{e.preventDefault();if(!$('player-name').value.trim()||state.traits.length!==3){error.textContent='Enter a name and choose exactly three traits.';error.hidden=false;return}state.name=$('player-name').value.trim();sessionStorage.setItem('miraculousCharacter',JSON.stringify(state));location.href='review.html'});
const help=$('trait-help'),panel=$('trait-help-panel');help.addEventListener('click',()=>{const open=panel.hidden;panel.hidden=!open;help.setAttribute('aria-expanded',String(open))});
const dialog=$('settings-dialog');$('settings-toggle').addEventListener('click',()=>dialog.showModal());$('close-settings').addEventListener('click',()=>dialog.close());$('text-color').addEventListener('input',e=>{state.textColor=e.target.value;document.documentElement.style.setProperty('--text',state.textColor)});$('sound-toggle').addEventListener('click',e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'🔊':'🔇';e.currentTarget.setAttribute('aria-pressed',String(state.sound))});refresh();
